CREATE TABLE `EMPLOYEE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` varchar(50) NOT NULL,
  `MIDDLE_NAME` varchar(50) DEFAULT NULL,
  `LAST_NAME` varchar(50) NOT NULL,
  `TEL_NO` varchar(15) DEFAULT NULL,
  `EMAIL_ADDRESS` varchar(25) DEFAULT NULL,
  `SKILL` varchar(255) DEFAULT NULL,
  `RATE` double DEFAULT NULL,
  `STATUS` varchar(1) DEFAULT NULL,
  `CREATED_TS` datetime NOT NULL,
  `MODIFIED_TS` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

