CREATE TABLE `ORGANIZATION` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(100) NOT NULL,
  `ADDRESS` varchar(255) DEFAULT NULL,
  `TEL_NO` varchar(15) DEFAULT NULL,
  `CONTACT_PERSON` varchar(100) DEFAULT NULL,
  `TYPE` varchar(25) DEFAULT NULL,
  `STATUS` varchar(1) NOT NULL,
  `CREATED_TS` datetime NOT NULL,
  `MODIFIED_TS` datetime NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

