CREATE TABLE `SHIFT_STATUS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `STATUS_CODE` varchar(20) NOT NULL,
  `STATUS_DESC` varchar(20) NOT NULL,  
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;